import { Specialty, Doctor } from './types';

export const TRANSLATIONS = {
  en: {
    hospital_name: "MEDLINK HOSPITAL",
    hospital_tagline: "Hospital & Medical Center",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email Address",
    password: "Password",
    first_name: "First Name",
    last_name: "Last Name",
    phone: "Phone Number",
    address: "Address",
    role: "Role",
    book_appointment: "Book Appointment",
    patient_dashboard: "Patient Central",
    doctor_dashboard: "Doctor Workspace",
    confirm_payment: "Confirm Payment",
    success: "Success!",
    specialty: "Medical Specialty",
    select_doctor: "Select Doctor",
    select_slot: "Pick a Time",
    receipt: "Download Receipt",
    welcome: "Welcome to our care network",
    secure_login: "Secure Login",
    create_account: "Create Account",
    forgot_access: "Forgot Access Key?",
    chat_title: "MedLink Assistant",
    chat_placeholder: "Type your message...",
    chat_disclaimer: "AI Assistant: For information only, not medical advice.",
    chat_welcome: "Hello! How can I assist you with MedLink Hospital today?",
  },
  gu: {
    hospital_name: "મેડલિંક હોસ્પિટલ",
    hospital_tagline: "હોસ્પિટલ અને મેડિકલ સેન્ટર",
    login: "લોગિન",
    register: "રજીસ્ટર",
    logout: "લોગ આઉટ",
    email: "ઈમેઈલ સરનામું",
    password: "પાસવર્ડ",
    first_name: "પ્રથમ નામ",
    last_name: "અટક",
    phone: "ફોન નંબર",
    address: "સરનામું",
    role: "ભૂમિકા",
    book_appointment: "મુલાકાત બુક કરો",
    patient_dashboard: "પેશન્ટ સેન્ટ્રલ",
    doctor_dashboard: "ડોક્ટર કાર્યસ્થળ",
    confirm_payment: "ચુકવણી કન્ફર્મ કરો",
    success: "સફળતા!",
    specialty: "તબીબી વિશેષતા",
    select_doctor: "ડોક્ટર પસંદ કરો",
    select_slot: "સમય પસંદ કરો",
    receipt: "રસીદ ડાઉનલોડ કરો",
    welcome: "અમારા કેર નેટવર્કમાં આપનું સ્વાગત છે",
    secure_login: "સુરક્ષિત લોગિન",
    create_account: "ખાતું બનાવો",
    forgot_access: "પાસવર્ડ ભૂલી ગયા છો?",
    chat_title: "મેડલિંક સહાયક",
    chat_placeholder: "તમારો સંદેશ લખો...",
    chat_disclaimer: "AI સહાયક: ફક્ત માહિતી માટે, તબીબી સલાહ નથી.",
    chat_welcome: "નમસ્તે! આજે હું તમને મેડલિંક હોસ્પિટલ વિશે કેવી રીતે મદદ કરી શકું?",
  },
  hi: {
    hospital_name: "मेडलिंक अस्पताल",
    hospital_tagline: "अस्पताल और चिकित्सा केंद्र",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉग आउट",
    email: "ईमेल पता",
    password: "पासवर्ड",
    first_name: "पहला नाम",
    last_name: "उपनाम",
    phone: "फ़ोन नंबर",
    address: "पता",
    role: "भूमिका",
    book_appointment: "अपॉइंटमेंट बुक करें",
    patient_dashboard: "पेशेंट सेंट्रल",
    doctor_dashboard: "डॉक्टर वर्कस्पेस",
    confirm_payment: "भुगतान की पुष्टि करें",
    success: "सफलता!",
    specialty: "चिकित्सा विशेषता",
    select_doctor: "डॉक्टर चुनें",
    select_slot: "समय चुनें",
    receipt: "रसीद डाउनलोड करें",
    welcome: "हमारे केयर नेटवर्क में आपका स्वागत है",
    secure_login: "सुरक्षित लॉगिन",
    create_account: "खाता बनाएँ",
    forgot_access: "पासवर्ड भूल गए?",
    chat_title: "मेडलिंक सहायक",
    chat_placeholder: "अपना संदेश लिखें...",
    chat_disclaimer: "AI सहायक: केवल जानकारी के लिए, चिकित्सा सलाह नहीं।",
    chat_welcome: "नमस्ते! आज मैं मेडलिंक अस्पताल के बारे में आपकी क्या सहायता कर सकता हूँ?",
  }
};

export const SPECIALTIES: Specialty[] = [
  'General Practice',
  'Pediatrics',
  'Cardiology',
  'Dentistry',
  'Gynecology',
  'Neurology',
  'Orthopedics'
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'd1',
    email: 'sarah.jones@medlink.com',
    firstName: 'Sarah',
    lastName: 'Jones',
    address: '123 Medical Way',
    phone: '555-0101',
    role: 'DOCTOR',
    specialty: 'Pediatrics',
    bio: 'Specialist in newborn care and adolescent medicine with 12 years of experience.',
    experienceYears: 12
  },
  {
    id: 'd2',
    email: 'mark.smith@medlink.com',
    firstName: 'Mark',
    lastName: 'Smith',
    address: '456 Health St',
    phone: '555-0102',
    role: 'DOCTOR',
    specialty: 'Cardiology',
    bio: 'Board-certified cardiologist focusing on preventative heart health and diagnostic imaging.',
    experienceYears: 15
  },
  {
    id: 'd3',
    email: 'elena.rodriguez@medlink.com',
    firstName: 'Elena',
    lastName: 'Rodriguez',
    address: '789 Care Blvd',
    phone: '555-0103',
    role: 'DOCTOR',
    specialty: 'Dentistry',
    bio: 'Expert in cosmetic dentistry, oral surgery, and pediatric dental health.',
    experienceYears: 8
  },
  {
    id: 'd4',
    email: 'david.chen@medlink.com',
    firstName: 'David',
    lastName: 'Chen',
    address: '101 Wellness Lane',
    phone: '555-0104',
    role: 'DOCTOR',
    specialty: 'Gynecology',
    bio: 'Compassionate care for women’s reproductive health and prenatal management.',
    experienceYears: 20
  },
  {
    id: 'd5',
    email: 'michael.miller@medlink.com',
    firstName: 'Michael',
    lastName: 'Miller',
    address: '202 Bone Ave',
    phone: '555-0105',
    role: 'DOCTOR',
    specialty: 'Orthopedics',
    bio: 'Specializes in sports injuries and joint replacement surgery.',
    experienceYears: 10
  },
  {
    id: 'd6',
    email: 'lisa.wong@medlink.com',
    firstName: 'Lisa',
    lastName: 'Wong',
    address: '303 Brain St',
    phone: '555-0106',
    role: 'DOCTOR',
    specialty: 'Neurology',
    bio: 'Expert in treating migraine, epilepsy, and cognitive disorders.',
    experienceYears: 18
  },
  {
    id: 'd7',
    email: 'james.wilson@medlink.com',
    firstName: 'James',
    lastName: 'Wilson',
    address: '404 General Rd',
    phone: '555-0107',
    role: 'DOCTOR',
    specialty: 'General Practice',
    bio: 'Primary care physician focusing on family wellness and chronic disease management.',
    experienceYears: 25
  },
  {
    id: 'd8',
    email: 'emily.brown@medlink.com',
    firstName: 'Emily',
    lastName: 'Brown',
    address: '505 Kids Ln',
    phone: '555-0108',
    role: 'DOCTOR',
    specialty: 'Pediatrics',
    bio: 'Dedicated to providing comprehensive care for children from birth through young adulthood.',
    experienceYears: 6
  },
  {
    id: 'd9',
    email: 'robert.taylor@medlink.com',
    firstName: 'Robert',
    lastName: 'Taylor',
    address: '606 Heart Way',
    phone: '555-0109',
    role: 'DOCTOR',
    specialty: 'Cardiology',
    bio: 'Interventional cardiologist specializing in minimally invasive cardiac procedures.',
    experienceYears: 22
  },
  {
    id: 'd10',
    email: 'sofia.garcia@medlink.com',
    firstName: 'Sofia',
    lastName: 'Garcia',
    address: '707 Smile Blvd',
    phone: '555-0110',
    role: 'DOCTOR',
    specialty: 'Dentistry',
    bio: 'Focuses on restorative dentistry and patient comfort.',
    experienceYears: 14
  }
];

export const SLOTS = [
  "09:00", "09:30", "10:00", "10:30", "11:00", "11:30",
  "14:00", "14:30", "15:00", "15:30", "16:00", "16:30"
];
